# Generated by Django 5.2.7 on 2025-10-17 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('author_workplace', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('views', models.IntegerField(default=0)),
                ('language', models.CharField(choices=[('tm', 'Turkmen'), ('ru', 'Russian'), ('en', 'English')], default='tm', max_length=2)),
                ('type', models.CharField(choices=[('local', 'Local'), ('foreign', 'Foreign')], default='local', max_length=7)),
                ('publication_date', models.DateField()),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('newspaper_or_journal', models.CharField(blank=True, max_length=255, null=True)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarked_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
