# Generated by Django 5.2.7 on 2025-10-23 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=100)),
                (
                    "author_workplace",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rating", models.FloatField(default=0.0)),
                ("views", models.IntegerField(default=0)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("tm", "Turkmen"),
                            ("ru", "Russian"),
                            ("en", "English"),
                        ],
                        default="tm",
                        max_length=2,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("local", "Local"), ("foreign", "Foreign")],
                        default="local",
                        max_length=7,
                    ),
                ),
                ("publication_date", models.DateField()),
                (
                    "source_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                (
                    "newspaper_or_journal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bookmarks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bookmarked_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="content.articlecategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="content.bookcategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "epub_file",
                    models.FileField(blank=True, null=True, upload_to="books/epub/"),
                ),
                ("author", models.CharField(max_length=100)),
                ("rating", models.FloatField(default=0.0)),
                ("views", models.IntegerField(default=0)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("tm", "Turkmen"),
                            ("ru", "Russian"),
                            ("en", "English"),
                        ],
                        default="tm",
                        max_length=2,
                    ),
                ),
                (
                    "bookmarks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bookmarked_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="books", to="content.bookcategory"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DissertationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="content.dissertationcategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Dissertation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=100)),
                (
                    "author_workplace",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rating", models.FloatField(default=0.0)),
                ("views", models.IntegerField(default=0)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("tm", "Turkmen"),
                            ("rm", "Russian"),
                            ("en", "English"),
                        ],
                        default="tm",
                        max_length=2,
                    ),
                ),
                ("publication_date", models.DateField()),
                (
                    "bookmarks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bookmarked_dissertations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dissertations",
                        to="content.dissertationcategory",
                    ),
                ),
            ],
        ),
    ]
