# Generated by Django 5.2.7 on 2025-10-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlecategory",
            options={"verbose_name_plural": "Article Categories"},
        ),
        migrations.AlterModelOptions(
            name="bookcategory",
            options={"verbose_name_plural": "Book Categories"},
        ),
        migrations.AlterModelOptions(
            name="dissertationcategory",
            options={"verbose_name_plural": "Dissertation Categories"},
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="books/covers/"),
        ),
    ]
