# Generated by Django 5.2.7 on 2025-10-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_articlecategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dissertation",
            name="language",
            field=models.CharField(
                choices=[("tm", "Turkmen"), ("ru", "Russian"), ("en", "English")],
                default="tm",
                max_length=2,
            ),
        ),
    ]
