# Generated by Django 5.2.7 on 2025-11-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_dissertation_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="books/article_images/"
            ),
        ),
    ]
