# Generated by Django 5.2.7 on 2025-11-20 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_alter_article_content_alter_book_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="bookmarks",
        ),
        migrations.RemoveField(
            model_name="book",
            name="bookmarks",
        ),
        migrations.RemoveField(
            model_name="dissertation",
            name="bookmarks",
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bookmarks_articles",
                    models.ManyToManyField(
                        blank=True, related_name="bookmarked_by", to="content.article"
                    ),
                ),
                (
                    "bookmarks_books",
                    models.ManyToManyField(
                        blank=True, related_name="bookmarked_by", to="content.book"
                    ),
                ),
                (
                    "bookmarks_dissertations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bookmarked_by",
                        to="content.dissertation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
