# Generated by Django 5.2.7 on 2025-11-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_article_average_rating_article_rating_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_articles",
                to="content.articlecategory",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_books", to="content.bookcategory"
            ),
        ),
        migrations.AlterField(
            model_name="dissertation",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_dissertations",
                to="content.dissertationcategory",
            ),
        ),
    ]
