# Generated by Django 5.2.7 on 2025-11-27 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_alter_article_categories_alter_book_categories_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bookmarks_articles",
            new_name="bookmarked_articles",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="bookmarks_books",
            new_name="bookmarked_books",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="bookmarks_dissertations",
            new_name="bookmarked_dissertations",
        ),
    ]
