# Generated by Django 5.2.7 on 2025-11-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0009_rename_bookmarks_articles_profile_bookmarked_articles_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="content.articlecategory"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="content.bookcategory"
            ),
        ),
        migrations.AlterField(
            model_name="dissertation",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="dissertations",
                to="content.dissertationcategory",
            ),
        ),
    ]
