# Generated by Django 5.2.7 on 2025-12-19 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="article_views_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="article_language_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="article_pubdate_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="book_views_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="book_language_idx",
        ),
        migrations.RemoveIndex(
            model_name="dissertation",
            name="dissertation_views_idx",
        ),
        migrations.RemoveIndex(
            model_name="dissertation",
            name="dissertation_language_idx",
        ),
        migrations.RemoveIndex(
            model_name="dissertation",
            name="dissertation_pubdate_idx",
        ),
    ]
