# Generated by Django 5.2.7 on 2025-12-20 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0014_add_viewrecord"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="viewrecord",
            new_name="content_vie_session_2bc873_idx",
            old_name="viewrec_sess_ct_cid_idx",
        ),
        migrations.RenameIndex(
            model_name="viewrecord",
            new_name="content_vie_user_id_cf26d5_idx",
            old_name="viewrec_user_ct_cid_idx",
        ),
    ]
