# Generated by Django 5.2.7 on 2025-12-24 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0015_rename_viewrec_sess_ct_cid_idx_content_vie_session_2bc873_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="language",
            field=models.CharField(
                choices=[("tm", "Turkmen"), ("ru", "Russian"), ("en", "English")],
                db_index=True,
                default="tm",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="type",
            field=models.CharField(
                choices=[("local", "Local"), ("foreign", "Foreign")],
                db_index=True,
                default="local",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="views",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(
                choices=[("tm", "Turkmen"), ("ru", "Russian"), ("en", "English")],
                db_index=True,
                default="tm",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="dissertation",
            name="language",
            field=models.CharField(
                choices=[("tm", "Turkmen"), ("ru", "Russian"), ("en", "English")],
                db_index=True,
                default="tm",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="dissertation",
            name="publication_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="dissertation",
            name="views",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="contentrating",
            index=models.Index(
                fields=["content_type", "content_id"],
                name="content_con_content_50a646_idx",
            ),
        ),
    ]
