# Generated by Django 5.2.7 on 2025-12-26 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_recommend_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="article_lang_pubdate_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="article_type_lang_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="book_lang_views_idx",
        ),
        migrations.RemoveIndex(
            model_name="dissertation",
            name="dissertation_lang_pubdate_idx",
        ),
    ]
